=== ofk16fsm/PythonXmlGenerator/Xml_generator/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema">
	<xsi:element name="products" type="productsType"></xsi:element>	
	<xsi:complexType name="productsType">
		<xsi:sequence>
            <xsi:element name="product" type="productType" maxOccurs="unbounded"></xsi:element>
        </xsi:sequence>
    </xsi:complexType>
	
	<xsi:complexType name="productType">
        <xsi:sequence>
            <xsi:element name="id" type="xsi:integer"/>
            <xsi:element name="name" type="xsi:string"/>
            <xsi:element name="price" type="xsi:integer"/>
            <xsi:element name="type" type="xsi:string"/>
            <xsi:element name="playtime" type="xsi:integer"/>
        </xsi:sequence>
    </xsi:complexType>
</xsi:schema>

=== ofk16fsm/PythonXmlGenerator/Xml_generator/products.xml
<?xml version="1.0" encoding="utf-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
  <product>
    <id>202102</id>
    <name>Gudfadern</name>
    <price>99</price>
    <type>DVD</type>
    <playtime>152</playtime>
  </product>
  <product>
    <id>102342</id>
    <name>Pulp fiction</name>
    <price>99</price>
    <type>DVD</type>
    <playtime>154</playtime>
  </product>
  <product>
    <id>201548</id>
    <name>Schindlers list</name>
    <price>149</price>
    <type>DVD</type>
    <playtime>195</playtime>
  </product>
</products>
